### ISSUE TITLE
Dados equivocados 

### ISSUE THREAD

**Issue by GreedBlink** [pedrocostaferreira/BETS#1]
A tabela de metadados (bacen-v7) contém algumas informações erradas. O campo 'start' frequentemente não contém a verdadeira data de início da série.

**Comment by GreedBlink** [comment]
A API utilizada para pegar os dados das séries foi configurada para pegar no intervalo de tempo entre 1990 até a data atual.

Alguns retornos da função BETSsearch possuem alguns erros de preenchimento, tal problema pode ser gerado pelo fato do sistema de localização de séries temporais do banco central exportar os metadados em csv (DOS) e ligando ao fato que algumas descrições de séries possuem "," ,os dados são  organizados de forma errada pelo R.  O problema é gerado, mesmo usando diferentes tipos de leituras.

**Comment by talithafs** [comment]
O problema é no site do BC. Não temos muito poder aqui.
