### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by talithafs** [pedrocostaferreira/BETS#15]
Se os pacotes `fracdiff`, `colorspace`, `timeDate` e `tseries` não estiverem instalados previamente, a instalação do BETS falha.

**Comment by talithafs** [comment]
**Diagnóstico do problema** 

Primeiro, desinstalei os pacotes da minha biblioteca, fazendo:

`remove.packages(c("fracdiff","tseries","timeDate","colorspace"))`

Então, abri o projeto do BETS e executei o comando:

`devtools.check()`

Com isso, descobri que o BETS não poderia ser instalado porque o pacote `ggplot2`, que é importado pelo BETS, não estava funcionando. O motivo era a ausência de alguma dependência, mas a função `devtools.check()` não reportou qual era. Então, carreguei o pacote `ggplot2` e vi que o problema era a ausência do pacote `colorspace`. Desistalei o `ggplot2` e tentei instalá-lo requisitando explicitamente que suas dependências fossem instaladas, da seguinte maneira:

`install.packages("ggplot2", dependencies = TRUE)`

No entanto, o pacote `colorspace` não foi instalado. A única solução é instalá-lo manualmente, antes ou depois de instalar o `ggplot2`.

Após reinstalar o `colorspace`, rodei novamente a função `devtools.check()` e, dessa vez, descobri que o pacote `forecast`, importado pelo BETS, também não poderia funcionar. Carregando-o no console, vi que as dependências `fracdiff`,`tseries`,`timeDate` estavam ausentes. Removi, então, o pacote `forecast` e tentei reinstalá-lo com o parâmetro `dependencies = TRUE`. Os pacotes `fracdiff`,`tseries`,`timeDate`  foram instalados corretamente.

**Soluções**

Bastaria que encontrássemos uma maneira de forçar que as dependências dos pacotes importados também fossem instaladas. Evidentemente, essa solução não funcionaria para o caso do `colorspace`, pois trata-se de um erro que ainda não consegui compreender, mas que certamente não tem relação com o BETS. Algumas pessoas relataram o mesmo problema, mas a única maneira de resolver parece ser instalá-lo manualmente ou, equivalentemente, incluí-lo na lista de `Imports` no arquivo `DESCRIPTION` do BETS. 

Acredito que haja uma solução para os outros 3 pacotes que não seja também incluí-los na lista de `Imports`, pois isso não faria muito sentido. Entretanto, na falta de outra solução melhor, é o que farei por agora. 

OBS: A possiblidade de usar `install_github("pedrocostaferreira/BETS", dependencies = TRUE)` para resolver o problema já foi descartada. Não funciona. Instalaria apenas as dependências do BETS listadas sob `Depends` (arquivo `DESCRIPTION`)

**Comment by talithafs** [comment]
**Importante:** Precisamos verificar se outros pacotes importados estão causando este problema. Sabem se há alguma maneira automática de encontrar as dependências de um pacote ou teremos que ler manual por manual (na verdade, arquivos DESCRIPTION)?

**Comment by pedrocostaferreira** [comment]
O problema persiste. Mesmo instalando separadamente todos os pacotes abaixo, a mensagem de erro permace.

**install.packages("tseries")
install.packages("timeDate")
install.packages("fracdiff")
install.packages("colorspace")
install.packages("gtable")
install.packages("scales")
install.packages("numDeriv")
install.packages("spd")
install.packages("Rsolnp")
install.packages("base64enc")
install.packages("ks")
install.packages("htmlwidgets")
install.packages("SkewHyperbolic")
install.packages("expm")
install.packages("tidyr")
install.packages("RSQLite")
install.packages('gsubfn')
install.packages("'viridis")
install.packages("chron")
install.packages("xts")
install.packages("nloptr")
install.packages("xlsx")**

Eu tentei instalar novamente e o BETS gerou a mesma mensagem de erro ("there is no package called ....") para os seguintes pacotes:

quadprog
Rcpp
gtable
scales
base64enc
htmlwidgets
viridis
rmarkdown

**Comment by talithafs** [comment]
Foi aquilo que falei na mensagem anterior. Os pacotes na lista de `Imports` do BETS não são instalados com as suas dependências, então temos que checar pacote por pacote e então listar suas dependências manualmente em `Imports` ou arrumar uma solução mais elegante (a lista provavelmente ficaria MUITO grande, de uma maneira que eu, pelo menos, nunca vi)

**Comment by GreedBlink** [comment]
Existe uma função chamada `dependsOnPkgs` que basicamente mostra os `imports` e de `depends` dos pacotes inseridos como argumento. 

Forma de uso: `dependsOnPkgs(pkgs,
              dependencies = c("Depends", "Imports", "LinkingTo"),
              recursive = TRUE, lib.loc = NULL,
              installed =
              utils::installed.packages(lib.loc, fields = "Enhances"))`

Para saber mais: acesse [aqui](https://stat.ethz.ch/R-manual/R-devel/library/tools/html/dependsOnPkgs.html)

Rodando a função para os pacotes listados pelo Pedro, temos:

`dependsOnPkgs(c("rootSolve", "ggplot2", "plotly", "urca", "TTR", "forecast", "TSA", "FinTS", "fpp", "stringi", "sqldf", "foreign", "lmtest", "normtest", "zoo",  "rugarch", "xlsx", "colorspace", "fracdiff", "tseries", "timeDate"))`

Saída:

`[1] "BETS"          "Deducer"      
 [3] "dynlm"         "effects"      
 [5] "expsmooth"     "fma"          
 [7] "Infer"         "munsell"      
 [9] "sandwich"      "stringr"      
[11] "tidyr"         "viridis"      
[13] "xts"           "DeducerExtras"
[15] "lubridate"     "multcomp"     
[17] "reshape2"      "scales"       
[19] "leaflet"      
`

Rodando um a um :
`> dependsOnPkgs("rootSolve")
[1] "BETS"

> dependsOnPkgs("ggplot2")
> [1] "BETS"          "Deducer"  
> [3] "forecast"      "plotly"  
> [5] "viridis"       "DeducerExtras"
> [7] "expsmooth"     "fma"  
> [9] "fpp"  
> dependsOnPkgs("plotly")
> [1] "BETS"
> dependsOnPkgs("urca")
> [1] "BETS"  "Infer"
> dependsOnPkgs("TTR")
> [1] "BETS"
> dependsOnPkgs( "forecast")
> [1] "BETS"      "expsmooth"
> [3] "fma"       "fpp"  
> dependsOnPkgs("TSA")
> [1] "BETS"  "Infer"
> dependsOnPkgs("FinTS")
> [1] "BETS"
> dependsOnPkgs( "fpp")
> [1] "BETS"
> dependsOnPkgs("stringi")
>  [1] "BETS"          "stringr"  
>  [3] "tidyr"         "lubridate"  
>  [5] "plotly"        "reshape2"  
>  [7] "ggplot2"       "Infer"  
>  [9] "Deducer"       "forecast"  
> [11] "viridis"       "DeducerExtras"
> [13] "expsmooth"     "fma"  
> [15] "fpp"  
> dependsOnPkgs("sqldf")
> [1] "BETS"
> dependsOnPkgs("foreign")
> [1] "BETS"          "Deducer"  
> [3] "DeducerExtras"
> dependsOnPkgs("lmtest")
> [1] "BETS"  "dynlm" "fpp"   "Infer"
> dependsOnPkgs( "normtest")
> [1] "BETS"
> dependsOnPkgs("zoo")
>  [1] "BETS"          "dynlm"  
>  [3] "FinTS"         "forecast"  
>  [5] "Infer"         "lmtest"  
>  [7] "rugarch"       "sandwich"  
>  [9] "tseries"       "TTR"  
> [11] "xts"           "expsmooth"  
> [13] "fma"           "fpp"  
> [15] "multcomp"      "TSA"  
> [17] "Deducer"       "DeducerExtras"
> dependsOnPkgs("rugarch")
> [1] "BETS"
> dependsOnPkgs("xlsx")
> [1] "BETS"
> dependsOnPkgs("colorspace")
>  [1] "BETS"          "effects"  
>  [3] "forecast"      "munsell"  
>  [5] "Deducer"       "expsmooth"  
>  [7] "fma"           "fpp"  
>  [9] "scales"        "DeducerExtras"
> [11] "ggplot2"       "leaflet"  
> [13] "plotly"        "viridis"  
> dependsOnPkgs("fracdiff")
> [1] "BETS"      "forecast" 
> [3] "expsmooth" "fma"  
> [5] "fpp"  
> dependsOnPkgs("tseries")
> [1] "BETS"      "fma"  
> [3] "forecast"  "fpp"  
> [5] "TSA"       "expsmooth"
> [7] "Infer"  
> dependsOnPkgs("timeDate")
> [1] "BETS"      "forecast" 
> [3] "expsmooth" "fma"  
> [5] "fpp"  
> `

**Comment by talithafs** [comment]
Mas essa função ta mostrando as dependências reversas, não? Tipo, quais pacotes dependem de cada pacote da lista que você passa como argumento, certo? 

Acho que precisamos do contrário. Encontrei um pacote, chamado `miniCRAN` que faz isso. Mostra até um grafo com as dependências recursivas (tem que instalar o pacote `igraph` antes pra ver o grafo). 

Exemplos aqui: https://cran.r-project.org/web/packages/miniCRAN/vignettes/miniCRAN-dependency-graph.html 

Os resultados são um pouco alarmantes. São MUITOS pacotes. Teremos mesmo que encontrar uma maneira de exigir que a instalação busque as dependências sozinha

**Comment by GreedBlink** [comment]
Verdade, vou dar uma olhada aqui!

Coloca a saída da função aew.

**Comment by talithafs** [comment]
Se você rodar

`plot(miniCRAN::makeDepGraph("forecast"))`

Vai obter

![graph](https://cloud.githubusercontent.com/assets/14915238/17528490/10e97ffe-5e46-11e6-8d5b-18d6c4d35ede.png)

Tenso!

**Comment by GreedBlink** [comment]
Talitha, você já deu uma olhada no `warning` sobre o last_plot? 

Toda vez que a instalação do `BETS` é concluída aparece esse aviso: 

`Warning: replacing previous import 'ggplot2::last_plot' by 'plotly::last_plot' when loading 'BETS'`

Parece que tanto o `ggplot2` e o `plotly` carregam `last_plot`. Isso devido ao fato que temos Import para os dois pacotes. É necessário ter os dois puxando a mesma função?

OBS. : [ Aqui](https://github.com/ropensci/plotly/issues/598) tem um issues tratando disso.

**Comment by talithafs** [comment]
Resolvido com a submissão ao CRAN.
