### ISSUE TITLE
Problema no carregamento do pacote

### ISSUE THREAD

**Issue by cdshikida1** [pedrocostaferreira/BETS#17]
Olá. Acabei de seguir os passos para instalar. Tudo ok. Mas ao carregar o BETS...bem, eis as mensagens da última etapa e da tentativa de carregamento. Será que há algum problema?

"C:/PROGRA~1/R/R-3.3.2/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/cdshi_000/AppData/Local/Temp/RtmpwnpxlU/devtoolsc702e7e1b0a/pedrocostaferreira-BETS-9c8357f"  \
  --library="C:/Users/cdshi_000/Documents/R/win-library/3.3"  \
  --install-tests 

* installing *source* package 'BETS' ...
** R
** inst
** tests
** preparing package for lazy loading
Warning in get0(".packageName", env, inherits = FALSE) :
  internal error -3 in R_decompress1
Error in get0(".packageName", env, inherits = FALSE) : 
  lazy-load database 'C:/Users/cdshi_000/Documents/R/win-library/3.3/urca/R/urca.rdb' is corrupt
ERROR: lazy loading failed for package 'BETS'
* removing 'C:/Users/cdshi_000/Documents/R/win-library/3.3/BETS'
* restoring previous 'C:/Users/cdshi_000/Documents/R/win-library/3.3/BETS'
Error: Command failed (1)
> library(BETS)
Error in get0(".packageName", env, inherits = FALSE) : 
  lazy-load database 'C:/Users/cdshi_000/Documents/R/win-library/3.3/urca/R/urca.rdb' is corrupt
In addition: Warning message:
In get0(".packageName", env, inherits = FALSE) :
  internal error -3 in R_decompress1
Error: package or namespace load failed for ‘BETS’

**Comment by talithafs** [comment]
Boa tarde, Cláudio! Lembro de ter falado com você pelo Facebook e você havia conseguido instalar o pacote, certo? Sugiro que você instale a nova versão que está no CRAN. Está bem melhor : ) 

Qualquer problema, por favor, pode reportar. A propósito, retiramos aquele exemplo que você disse que não funcionava. Estava defasado, mesmo. 

Muito obrigada por usar o BETS!

**Comment by cdshikida1** [comment]
Boa tarde, faz tempo, heim? Obrigado. Vou checar.


Obrigado / Thanks for your time and attention.

Claudio D. Shikida


Esta mensagem pode conter informação confidencial e/ou privilegiada. Se
você não for o destinatário ou a pessoa autorizada a receber esta mensagem,
não poderá usar, copiar ou divulgar as informações nela contidas ou tomar
qualquer ação baseada nessas informações. Se você recebeu esta mensagem por
engano, por favor avise imediatamente o remetente, respondendo o presente
e-mail e apague-o em seguida.
This message may contain confidential and/or privileged information. If you
are not the addressee or authorized to receive this for the addressee, you
must not use, copy, disclose or take any action based on this message or
any information herein. If you have received this message in error, please
advise the sender immediately by reply e-mail and delete this message.

2017-04-26 16:40 GMT-03:00 Talitha Speranza <notifications@github.com>:

**Comment by cdshikida1** [comment]
Boa tarde! Faz tempo! Obrigado. Vou lá olhar.

**Comment by talithafs** [comment]
É verdade, Cláudio. Desculpe! Mas, por questões aqui da FGV, nós só conseguimos atualizar o pacote no CRAN há pouquíssimo tempo. De qualquer forma, me despreocupei quando conversamos (acho que numa troca de comentários) e vi que você tinha conseguido instalar o pacote : )

**Comment by cdshikida1** [comment]
Sem problema, meu comentário foi mais no sentido de ser supreendido do que de reclamar de alguma demora. Belo pacote vocês fizeram! Obrigado
