### ISSUE TITLE
Séries de Incerteza Econômica

### ISSUE THREAD

**Issue by analisemacro** [pedrocostaferreira/BETS#18]
Olá, Pessoal, parabéns pelo pacote, muito bom. Eu tentei pegar as séries de incerteza econômica (códigos 100.0, 100.1, 100.2 100.3), mas elas ou retornam valores estranhos, ou não retornam nada. 

Essas séries, em particular, não estão disponíveis?

Desde já agradeço. 

Abs

**Comment by GreedBlink** [comment]
Olá, 

Durante esses dias a API do banco central anda instável comprometendo o request dos dados.  Esse é um problema com o sistema localizador de séries do Banco Central e acreditamos que será resolvido em poucos dias. 

Forte abraço!

**Comment by talithafs** [comment]
Só complementando o Jonatha: 

De fato, as séries do BC podem demorar a vir, ou virem numa 2a tentativa . Mas as séries de incerteza entrarão amanhã, com a base de dados do IBRE.  Avisaremos quando ficarem disponíveis. 

Muito obrigada por testarem o BETS : )

**Comment by analisemacro** [comment]
Ah, maravilha. Obrigado pela pronta resposta.

Abs

**Comment by talithafs** [comment]
Boa tarde, @analisemacro  : ) 

As séries do Índice de Incerteza estão na nova versão do BETS (0.3), que subiu esse fim de semana. Nos desculpamos pela demora. Estamos enfrentando algumas questões burocráticas. 

Acessem através dos códigos `ST_100.0`,` ST_100.1`, `ST_100.2` e `ST_100.3`

**Comment by analisemacro** [comment]
Muito obrigado, Talitha!

Abs
