### ISSUE TITLE
omitindo valores

### ISSUE THREAD

**Issue by fernote7** [pedrocostaferreira/BETS#19]
Na série do BC número 7 há uma discordância entre os valores apresentados quando a função get.serie.bacen(7) é rodada contra a BETS.get(7). Na primeira função há alguns períodos com NAs (exemplo: linha 4499) e estes são removidos pela função BETS.get.

**Comment by talithafs** [comment]
NAs não são mais removidos das séries e a inconsistencia está resolvida.
