### ISSUE TITLE
Dashboard de Crescimento

### ISSUE THREAD

**Issue by talithafs** [pedrocostaferreira/BETS#20]
Pedro e Fernando, que séries vocês achariam interessante incluir no dashboard de crescimento? Além de algumas mais óbvias, como produtividade, IGP-M e talvez o místico papelão ondulado...

**Comment by pedrocostaferreira** [comment]
Thalita,
acredito que nesse primeiro momento podíamos focar no dashboard do sentimento: "Sentiment Analysis dashboard". Neste dashboard teriam dados das sondagens (principalmente as nossas), dados do ICE, LEI, IIEBR, inflação+ tx de juros, etc, etc... Veja aquela apresentação do Aloísio que enviei e siga como exemplo, blz?!

**Comment by talithafs** [comment]
Ok, Pedro! Perguntei apenas porque faz parte do cronograma oficial e, ao contrário do dashboard de sondagem, não tinha referências como a apresentação a que você se referiu. 

Mas vou deixar a issue aqui pro futuro, então : )

**Comment by talithafs** [comment]
Ficou resolvido que, no BETS, entram apenas o relatório de conjuntura e o de business cycles.
