### ISSUE TITLE
Não consigo usar o pacote

### ISSUE THREAD

**Issue by econometricsbr** [pedrocostaferreira/BETS#21]
Oi, boa noite.

Pacote bem bacana, mas não consigo usar. Já tentei em várias versões do R, mas sempre dá isso daí:

BETS.search(description = "gdp accumulated", unit = "US", view = F)
Error in .local(drv, ...) : 
  Failed to connect to database: Error: Lost connection to MySQL server at 'reading authorization packet', system error: 10060

Alguma dica?

**Comment by talithafs** [comment]
Bom dia! : ) 

Obrigada por tentar usar o BETS! Temos uma dica, sim. O problema deve ser a versão mais nova do pacote RMySQL, que não funciona muito bem. Então, você deve tentar desinstalá-lo e instalar uma versão mais antiga. Assim:

```
remove.packages("RMySQL")
install.packages("devtools")
devtools::install_version("RMySQL", version = "0.10.9", repos = "http://cran.us.r-project.org") 
```

Espero ter ajudado.

**Comment by econometricsbr** [comment]
Show, agora deu certo!

Muito obrigado!
