### ISSUE TITLE
Porque tão grande?

### ISSUE THREAD

**Issue by Figuera** [pedrocostaferreira/BETS#24]
Olá, gostaria antes de tudo parabenizar o trabalho de vocês. Sempre acreditei que os dados brasileiros são de muito difícil acesso e compreensão, só depois de muito trabalho e estudo que eu, por exemplo, consegui ter uma dimensão razoável de onde achar o que.

Acredito que a iniciativa do BETS é um passo na direção correta disponibilizar com mais facilidade ampla gama de séries temporais brasileiras. Além de incentivar e facilitar o uso do R para cientistas de dados brasileiros.

Dito isso eu gostaria do poder fazer algumas observações.

Esta é a lista de "dependências" do BETS:

grnn,
ggplot2,
plotly,
urca,
forecast,
sqldf,
zoo,
rmarkdown,
foreign,
seasonal,
stringr,
dygraphs,
RCurl,
shiny (≥ 0.13),
miniUI (≥ 0.1.1),
rstudioapi (≥ 0.4),
DT,
webshot,
RMySQL,
DBI

É muito grande, mas não somente grande, é supérfluo. Dos pacotes desta lista que eu conheço alguns são de visualização (ggplot2), outros são de tratamento de séries de tempo (forecast e zoo), outro de tratamento de strings (stringr) e tem até um de comunicação com IDE mais popular do R (rstudioapi).

Nada disso me parece necessário para a única razão que me fez baixar esse pacote - ter acesso fácil a séries de tempo brasileiras. Me soam como sugestão de pacotes úteis e não como dependências necessárias para o funcionamento do BETS, ou estou errado?

Parece haver um entendimento que isso é bom. No página de ajuda do pacote:

"More importantly, it installs several consecrated packages for time series 
analysis, giving the user the option to perform a complete analysis without
having to worry about installing and loading other packages."

Não! Cada um sabe os pacotes de analise que usa e precisa. Eu entendo que isso pode ser bem visto por quem vem de softwares como EViews e STATA, ou para quem está começando com R, ou ainda ser útil se for para ser usado em algum tipo de curso ou apresentação. Mas como pacote público que visa disponibilizar uma funcionalidade que seja útil para todo mundo essas coisas são apenas distrações.

Seria possível disponibilizar uma versão do pacote que seja pequena, leve e com apenas aquela parte que o pacote faz algo que ninguém mas faz?

Afinal como diz um dos preceitos filosóficos do programadores:

["Do One Thing And Do It Well"](http://dotadiw.com/)

**Comment by daianemarcolino** [comment]
Eu concordo. Sugiro uma versão mais light do BETS somente voltada para o download das séries temporais. E para não perder as funções de análises restantes, outro pacote poderia ser criado só com isso. Assim teriam dois pacotes trabalhando em conjunto.
