### ISSUE TITLE
BETS não está funcionando

### ISSUE THREAD

**Issue by econometricsbr** [pedrocostaferreira/BETS#25]
Olá, pessoal, tudo bem?

Desculpa incomodar vocês, mas hoje não consegui usar o BETS. Fica dando o seguinte erro quando tento usar a função BETS.get:

Error in .local(drv, ...) : 
  Failed to connect to database: Error: Can't connect to MySQL server on '200.20.164.178' (0)

Estou usando o RMySQL versão 0.10.9, como vocês orientaram. 

Se puderem ajudar...

Abs

**Comment by talithafs** [comment]
Oi! Obrigada por usar o BETS : ) 

Esse problema ocorre porque a nova versão do pacote RMySQL não está funcionando direito com versões mais antigas do R. Pra contornar isso, você pode fazer duas coisas:

- Instalar a versão mais recente do R (3.4) OU
- Seguir as instruções que dou no README, disponível aqui no GitHub, na seção "Warning"

Espero ter ajudado!

**Comment by talithafs** [comment]
@econometricsbr , precisei atualizar o README para cobrir outros casos em que o RMySQL estava causando problemas. Também pode ser necessário instalar uma versão mais antiga do pacote DBI. Os comandos são:

```R
remove.packages(c("RMySQL","DBI"))
install.packages("devtools")
devtools::install_version("DBI", version = "0.5", repos = "http://cran.us.r-project.org")
devtools::install_version("RMySQL", version = "0.10.9", repos = "http://cran.us.r-project.org") 
```

**Comment by econometricsbr** [comment]
Obrigado, Talitha! Esse segundo ponto resolveu o problema. 

Abs

**Comment by talithafs** [comment]
@econometricsbr a nova versão acaba de ser aceita no CRAN. Problema resolvido : )
