### ISSUE TITLE
Error in BETS.get

### ISSUE THREAD

**Issue by guilbran** [pedrocostaferreira/BETS#26]
A função BETS.get não está funcionando adequadamente.
Abaixo os exemplos:
`> BETS.get(1455)`
`Error in `$<-.data.frame`(`*tmp*`, data, value = character(0)) : 
  replacement has 0 rows, data has 54`
`> BETS.get(22099)`
`Error in `$<-.data.frame`(`*tmp*`, "data", value = character(0)) : 
  replacement has 0 rows, data has 54`

**Comment by talithafs** [comment]
Vou verificar. @fernote7 e @GreedBlink  parece ser incompatibilidade entre o retorno da API do BACEN e a BETS.get . Isso já aconteceu antes. Essa API é muito instável

**Comment by GreedBlink** [comment]
Problema na `get.series.bacen()`! 

Na hora de capturar a saída da API do BACEN:

`<title>500 - Internal server error.</title>`
...
`<h3>There is a problem with the resource you are looking for, and it cannot be displayed`

**Comment by GreedBlink** [comment]
Função corrigida [commit](https://github.com/pedrocostaferreira/BETS/commit/ff496467f77dff72440bb4ab068d3215aff194a5?diff=split). BETS versão 0.3.2
