### ISSUE TITLE
Estabilidade

### ISSUE THREAD

**Issue by msperlin** [pedrocostaferreira/BETS#29]
Caro Pedro,

Tenho utilizado o BETS para coletar dados e pretendo inclui-lo em um trabalho sobre R em Economia e Finanças. 

Porém, noto a cada compilação do livro que o pacote está bastante instável. As vezes funciona e as vezes nao. No passado não era assim. Claramente existe um problema de versão com o RMySQL. Já instalei a versão requerida e, mesmo assim, não funciona: 

`Sorry, but it was not possible to connect to the server.
You want to install a development version of RMySQL and DBI package packages?
(This may solve the connection problem)[Y/n]n
Error in value[[3L]](cond) : Connetcion fail!`

Gostaria muito de incluir o pacote no livro, porém nao consigo ter a estabilidade necessária para trabalhar encima. Existe algum plano para resolver este problema de incompatibilidade?

Obrigado.

**Comment by GreedBlink** [comment]
Olá @msperlin , de fato o BETS está passando por problemas de instabilidades por conta da migração do servidor que utilizamos para armazenar nosso banco de dados. Porém estamos finalizando e resolvendo todos os problemas. 

Uma nova versão (`0.3.6`) está sendo compilada com as correções (CRAN e GitHub) e, sim, você poderá utilizá-lo em seu livro! 

Ficamos grato pelo contato!

**Comment by msperlin** [comment]
Obrigado pela resposta. Irei aguardar.

Abc.

**Comment by GreedBlink** [comment]
Ah @msperlin, por favor, utilize o repositório do NMECSYS(Núcleo de Métodos Estatísticos e Computacionais) em[nmecsys/BETS](https://github.com/nmecsys/BETS) para qualquer dúvida, issues  ou contribuições!  Lá que mantemos a versão mais atual do pacote!  

Abraço!!
