### ISSUE TITLE
Relatório de Inflação

### ISSUE THREAD

**Issue by talithafs** [pedrocostaferreira/BETS#3]
Criar um relatório automático com indicadores relacionados ao monitoramento da inflação, retirados das bases do BETS. 

Um bom benchmark é o dashboard da Brookings Institution, que pode ser encontrado aqui:

[Janet Yellen's Dashboard](http://www.brookings.edu/~/media/Multimedia/Interactives/2014/dashboard/datafiles/YellenDashPrintVersion.pdf)

**Comment by talithafs** [comment]
Sugestão de séries a serem utilizadas no relatório:

INFLAÇÃO
- **IPCA**, acumulado em 12 meses (código 13522) 
- **Núcleo do IPCA** (código 4466) 
- **Custo Unitário do Trabalho** (código 11777)

EMPREGO
- **PEA** (código 10810) 
- **PIA** (código 10800) 
- **Taxa de Desemprego** (código 10777)

CRESCIMENTO
- **Taxa de Variação Real do PIB**, acumulada em 12 meses (código 7326)
- **Produção Industrial**, com ajuste sazonal (código 21940)

JUROS
- **Taxa SELIC** (código 11)
- **Depósitos a prazo (CDB/RDB-pré-fixados)** (código 14)

**Comment by pedrocostaferreira** [comment]
1) Perfeito!! Meu único comentário é com relação ao núcleo pois estamos criando um núcleo melhor que o calculado atualmente pela FGV/IBGE. Mas, por enquanto, vamos manter esse núcleo mesmo.

2) Seria legal também fazer o mesmo para as informações do EUA usando os dados do FED.

**Comment by talithafs** [comment]
1) É verdade. Mas a série vai ser paga? Porque daí acho que seria mais jogo manter a do IBGE, já que as séries pagas entram com defasagem.

2) Concordo! Vou abrir uma issue pra isso, também.

**Comment by talithafs** [comment]
Outras séries que poderiam entrar, mas eu não sei se existem e/ou se já estão disponíveis no BETS e eu só não entrei com os termos de busca corretos:

INFLAÇÃO
- **Expectativas do Mercado em relação à Inflação** (poderia entrar com a série da média ou mediana dos top 5 do Focus, mas não sei se estão ou estarão no BETS)

EMPREGO
- **Taxa de Subemprego**
- **Taxa de Desemprego de Longa Duração**
- Alguma medida da **taxa natural de desemprego**

CRESCIMENTO
- Índice de Vendas de Imóveis
- Alguma medida da **taxa de crescimento normal do PIB**

TAXA DE JUROS
- **Expectativas de Mercado em relação à SELIC** + projeções do BACEN

O relatório da Brookings também inclui um índice de preços de imóveis na parte referente aos juros. Não sei se o quão relevante seria no caso brasileiro, mas imagino que seja análogo ao americano.

**Comment by pedrocostaferreira** [comment]
comentários:

**INFLAÇÃO**

Expectativas do Mercado em relação à Inflação (poderia entrar com a série da média ou mediana dos top 5 do Focus, mas não sei se estão ou estarão no BETS) --> é uma boa sim, a Anna já está capturando esses dados.

**EMPREGO**

Taxa de Subemprego --> não conheço, mas seria legal
Taxa de Desemprego de Longa Duração--> não conheço, mas seria legal
Alguma medida da taxa natural de desemprego --> tem alguém que já cacula?!

**CRESCIMENTO**

Índice de Vendas de Imóveis --> nesse momento não me preocuparia com essa info.
Alguma medida da taxa de crescimento normal do PIB --> está falando de pib natural?! dado as quedas abruptas dos últimos trim, parece o que o filtro hp não está funcionando muito bem. Mas seria legal ter uma medida desse tipo

TAXA DE JUROS
Expectativas de Mercado em relação à SELIC + projeções do BACEN  --> é uma boa sim

**Comment by talithafs** [comment]
Primeira versão completa e funcionando.
