### ISSUE TITLE
Error em dar load no BETS

### ISSUE THREAD

**Issue by Rafaeltdcs** [pedrocostaferreira/BETS#31]
```
library(BETS)
Error: package or namespace load failed for ‘BETS’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘vctrs’ 0.1.0 is being loaded, but >= 0.2.0 is required
```
Alguém poderia me ajudar com o erro?

**Comment by GreedBlink** [comment]
Olá, 

Verifique se você está utilizando a versão mais atualizada. Caso nao, utilize a versão do repositorio do nmecsys. 

`devtools::install_github('nmecsys/BETS')`
ou
`install.packageS('BETS')`

**Comment by Rafaeltdcs** [comment]
Usei o caminho pelo devtools e mandei atualizar todos os packages. Agora um novo erro:

```
package ‘digest’ successfully unpacked and MD5 sums checked
Error: Failed to install 'BETS' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
```

Tem ideia do que pode ser?

**Comment by GreedBlink** [comment]
Você precisa desinstalar o pacote digest e depois instalar ele novamente! Depois tente instalar o BETS.

**Comment by Rafaeltdcs** [comment]
Acho que era um erro de atulização do R. Reiniciei o PC e reinstalei pelo CRAN e deu certo. 
Obrigado!
