### ISSUE TITLE
Publicação do pacote no CRAN

### ISSUE THREAD

**Issue by pedrocostaferreira** [pedrocostaferreira/BETS#6]
a ideia é discutirmos o que está sendo feito para a publicação do pacote no CRAN

**Comment by talithafs** [comment]
Na página [Package Primer](http://kbroman.org/pkg_primer/pages/cran.html) encontrei um roteiro de como submeter um pacote ao CRAN. Com base nesse roteiro, acredito que devemos fazer o seguinte:
1. Eliminar **todos** os erros e _warnings_. Qualquer interrupção de fluxo desse tipo **impede a publicação do pacote**. Os principais erros já estão documentados aqui (marcados como bugs) e nos logs dos testes automáticos. Precisamos documentar também os _warnings_.
2. Refinar os exemplos da documentação e assegurar que **todos estejam funcionando**.
3. Rodar o pacote a partir do console padrão do R (e não do RStudio) e **garantir que o RStudio não é necessário para o usuário final.**
4. Testar no Linux e no Mac, possivelmente usando máquinas virtuais. Caso alguma função do pacote não rode nessas plataformas, **ele não será aceito**.
5. É fortemente recomendado que os documentos [Writing R Packages](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) e [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html) sejam lidos/revisados com atenção, de modo a corrigir qualquer desvio.

Além disso, devemos terminar de traduzir os arquivos _.rd_ e documentar algumas funções mais novas. Seria interessante, também, fornecer pelo menos um _vignette_, mas não é obrigatório.

**Comment by GreedBlink** [comment]
Talitha, como já tinha te mostrado. Segue os pacotes e funções que devem ser adicionados no NAMESPACE:

  `importFrom("grDevices", "dev.new", "dev.off", "pdf", "png")`
`
`importFrom("graphics", "abline", "arrows", "axis", "barplot", "legend",
             "lines", "mtext", "par", "points", "text")`

  `importFrom("stats", "as.ts", "end", "frequency", "na.omit", "plot.ts",
             "qnorm", "qt", "sd", "start", "time", "ts", "uniroot",
             "window")`

 `importFrom("utils", "View", "combn", "head", "read.csv2")`

**Comment by GreedBlink** [comment]
Atualmente o BETS está sem erro em sua estrutura. Existiam exemplos que usavam pacotes como o `forecast` e na hora de dar o `check` ele acusava problema. É normal  exemplos virem em forma de comentários.  

Agora há 6 Warning a respeito das documentações e do incov da base de dados do metadata UTF-8.

**Comment by talithafs** [comment]
Feito.
