### ISSUE TITLE
Conversão de datas

### ISSUE THREAD

**Issue by talithafs** [pedrocostaferreira/BETS#7]
Para alguma séries, aparece o seguinte erro:

**Error in charToDate(x): character string is not in a standard unambiguous format**

No log bacen_v7 há o registro de todas as séries para as quais a BETSget apresenta esse problema. Por exemplo:

```
!! ERROR in bacen_v7 when code = 67. MESSAGE = Error in charToDate(x): character string is not in a standard unambiguous format

!! ERROR in bacen_v7 when code = 68. MESSAGE = Error in charToDate(x): character string is not in a standard unambiguous format

!! ERROR in bacen_v7 when code = 69. MESSAGE = Error in charToDate(x): character string is not in a standard unambiguous format

!! ERROR in bacen_v7 when code = 70. MESSAGE = Error in charToDate(x): character string is not in a standard unambiguous format
```

**Comment by talithafs** [comment]
A `sqldf`está retornando data.frames em que a primeira coluna é composta de números inteiros negativos. Por exemplo, se a série de código `1178` (SELIC acumulada em 12 meses) é requisitada, a `sqldf` retorna um data.frame cujas 5 primeiras linhas são:

```
         data    valor
1 -719131 78163.74
2 -719103 77869.64
3 -719072 28698.83
4 -719042 28899.78
5 -718950 29005.72
6 -718919  28913.5
```

Não é possível converter esses inteiros negativos para datas. É necessário rever o procedimento de aquisição das séries, afim de colocar as datas em um formato interpretável. 

Vou mandar a issue para o Jonatha, que entende melhor.

**Comment by GreedBlink** [comment]
Vou verificar!

**Comment by GreedBlink** [comment]
Estou reprogramando e revisando os scripts de extração das séries para verificar em qual parte houve erro de interpretação das datas. Alguns problemas nas verificações dos limites de download de séries pelo sistema do banco central. 

Todas os scripts auxiliares estão sendo revisados, se necessário, atualizados e agrupados (verificando o que não funciona tb) em um único arquivo .R 

Quando terminar eu te passo Talitha! :v:

**Comment by talithafs** [comment]
Resolvido com a função do Fernando.
